from .cSharp import c_sharp_prompt
from .famosos import famosos_prompt
from .java import java_prompt
from .python import python_prompt
from .javaScript import java_script_prompt
from .quiz_prompt import quiz_prompt
from .musicas import musicas_prompt
from .jogos import jogos_prompt
from .filmes import filmes_prompt